use crate::domain::{position::Position, trade::{Fill, OrderRecord, OrderState}, wallet::WalletStats};
use chrono::Utc;
use rusqlite::{params, Connection, OptionalExtension};
use std::{fs, path::Path, sync::Mutex};
use thiserror::Error;

#[derive(Debug, Error)] pub enum StorageError { #[error("sqlite: {0}")] Sql(#[from] rusqlite::Error), #[error("serialization: {0}")] Json(#[from] serde_json::Error), #[error("filesystem: {0}")] Io(#[from] std::io::Error), #[error("storage mutex poisoned")] Poisoned }
pub struct StateStore { conn: Mutex<Connection> }
impl StateStore {
    pub fn open(path: impl AsRef<Path>)->Result<Self,StorageError>{let path=path.as_ref();if path != Path::new(":memory:"){if let Some(parent)=path.parent(){fs::create_dir_all(parent)?;}}let c=Connection::open(path)?;c.execute_batch("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS kv (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, idempotency_key TEXT UNIQUE NOT NULL, state TEXT NOT NULL, payload TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS fills (order_id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS observations (id INTEGER PRIMARY KEY, kind TEXT NOT NULL, observed_at TEXT NOT NULL, received_at TEXT NOT NULL, payload TEXT NOT NULL);")?;Ok(Self{conn:Mutex::new(c)})}
    fn conn(&self)->Result<std::sync::MutexGuard<'_,Connection>,StorageError>{self.conn.lock().map_err(|_|StorageError::Poisoned)}
    pub fn save_wallet(&self,w:&WalletStats)->Result<(),StorageError>{self.put(&format!("wallet:{}",w.wallet),w)} pub fn save_position(&self,p:&Position)->Result<(),StorageError>{self.put(&format!("position:{}",p.mint),p)}
    pub fn positions(&self)->Result<Vec<Position>,StorageError>{let c=self.conn()?;let mut st=c.prepare("SELECT value FROM kv WHERE key LIKE 'position:%'")?;st.query_map([],|r|r.get::<_,String>(0))?.map(|v|serde_json::from_str(&v?).map_err(StorageError::from)).collect()}
    pub fn save_fill(&self,fill:&Fill)->Result<(),StorageError>{let c=self.conn()?;c.execute("INSERT INTO fills(order_id,payload,created_at) VALUES(?1,?2,?3) ON CONFLICT(order_id) DO UPDATE SET payload=excluded.payload",params![fill.order_id,serde_json::to_string(fill)?,Utc::now().to_rfc3339()])?;Ok(())}
    pub fn record_observation<T:serde::Serialize>(&self,kind:&str,observed_at:chrono::DateTime<Utc>,received_at:chrono::DateTime<Utc>,value:&T)->Result<(),StorageError>{if observed_at>received_at{return Err(StorageError::Sql(rusqlite::Error::InvalidQuery));}let c=self.conn()?;c.execute("INSERT INTO observations(kind,observed_at,received_at,payload) VALUES(?1,?2,?3,?4)",params![kind,observed_at.to_rfc3339(),received_at.to_rfc3339(),serde_json::to_string(value)?])?;Ok(())}
    pub fn put<T:serde::Serialize>(&self,key:&str,value:&T)->Result<(),StorageError>{let c=self.conn()?;c.execute("INSERT INTO kv(key,value,updated_at) VALUES(?1,?2,?3) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at",params![key,serde_json::to_string(value)?,Utc::now().to_rfc3339()])?;Ok(())}
    pub fn get<T:serde::de::DeserializeOwned>(&self,key:&str)->Result<Option<T>,StorageError>{let c=self.conn()?;let raw:Option<String>=c.query_row("SELECT value FROM kv WHERE key=?1",params![key],|r|r.get(0)).optional()?;raw.map(|v|serde_json::from_str(&v)).transpose().map_err(Into::into)}
    pub fn reserve_order(&self,o:&OrderRecord)->Result<bool,StorageError>{let c=self.conn()?;let changed=c.execute("INSERT OR IGNORE INTO orders(id,idempotency_key,state,payload,updated_at) VALUES(?1,?2,?3,?4,?5)",params![o.id,o.idempotency_key,format!("{:?}",o.state),serde_json::to_string(o)?,Utc::now().to_rfc3339()])?;Ok(changed==1)}
    pub fn update_order(&self,o:&OrderRecord)->Result<(),StorageError>{let c=self.conn()?;c.execute("UPDATE orders SET state=?2,payload=?3,updated_at=?4 WHERE id=?1",params![o.id,format!("{:?}",o.state),serde_json::to_string(o)?,Utc::now().to_rfc3339()])?;Ok(())}
    pub fn incomplete_orders(&self)->Result<Vec<OrderRecord>,StorageError>{let c=self.conn()?;let mut st=c.prepare("SELECT payload FROM orders WHERE state IN ('Pending','Submitted','Unknown')")?;st.query_map([],|r|r.get::<_,String>(0))?.map(|x|serde_json::from_str(&x?).map_err(StorageError::from)).collect()}
    pub fn latch_kill_switch(&self,reason:&str)->Result<(),StorageError>{self.put("risk:kill_switch",&reason)} pub fn kill_switch_reason(&self)->Result<Option<String>,StorageError>{self.get("risk:kill_switch")}
}
#[cfg(test)] mod tests { use super::*; use crate::domain::trade::OrderState; #[test] fn duplicate_order_is_refused_after_restart() { let s=StateStore::open(":memory:").unwrap(); let o=OrderRecord{id:"a".into(),signal_id:"s".into(),mint:"m".into(),state:OrderState::Pending,idempotency_key:"same".into(),created_at:Utc::now(),signature:None,error:None};assert!(s.reserve_order(&o).unwrap());assert!(!s.reserve_order(&o).unwrap());} }
