use anyhow::Context;
use clap::{Parser,Subcommand};
use solana_smart_money_bot::{config::{load,types::Mode},data::rpc::RpcPool,economics::{break_even_calculator,BreakEvenInputs},execution::{Executor,JupiterExecutor,PaperExecutor},observability,runtime::process_jsonl,storage::StateStore};
use std::{fs,path::PathBuf,time::Duration};
#[derive(Parser)] #[command(name="solana-bot",about="Fail-closed Solana smart-money trading system")] struct Cli { #[command(subcommand)] command:Command }
#[derive(Subcommand)] enum Command { Economics{#[arg(long)]input:PathBuf}, Check{#[arg(long)]config:PathBuf}, Run{#[arg(long)]config:PathBuf} }
#[tokio::main] async fn main()->anyhow::Result<()> { let cli=Cli::parse(); match cli.command { Command::Economics{input}=>{let text=fs::read_to_string(&input).with_context(||format!("read {}",input.display()))?;let value:BreakEvenInputs=toml::from_str(&text).context("parse economic input TOML")?;println!("{}",serde_json::to_string_pretty(&break_even_calculator(&value)?)?)} Command::Check{config}=>check(config).await?,Command::Run{config}=>run(config).await? };Ok(()) }
async fn dependencies(config:&solana_smart_money_bot::config::types::Config)->anyhow::Result<(JupiterExecutor,StateStore)> {let rpc=RpcPool::new(config.rpc.http_endpoints.clone(),Duration::from_secs(config.rpc.request_timeout_secs))?;rpc.health().await.context("RPC health check")?;let state=StateStore::open(&config.storage.sqlite_path).context("persistence check")?;if state.kill_switch_reason()?.is_some(){anyhow::bail!("persisted kill switch is latched; operator review is required")};if !state.incomplete_orders()?.is_empty(){anyhow::bail!("unreconciled orders exist; refusing new entries")};let execution=JupiterExecutor::new(config.execution.jupiter_api_url.clone(),rpc,config.execution.live_signer_env.clone(),config.economics.max_quote_age_secs,config.execution.allowed_program_ids.clone())?;execution.health().await.context("execution health check")?;Ok((execution,state))}
async fn check(path:PathBuf)->anyhow::Result<()> {let c=load(path)?;let (_execution,_state)=dependencies(&c).await?;if c.mode==Mode::Live{let name=c.execution.live_signer_env.as_deref().context("missing live signer env")?;let value=std::env::var(name).context("live signer secret unavailable")?;let _:Vec<u8>=serde_json::from_str(&value).context("live signer is not JSON byte-array keypair material")?;}println!("configuration, persistence, RPC, and execution health are valid; mode={:?}",c.mode);Ok(())}
async fn run(path:PathBuf)->anyhow::Result<()> {let c=load(path)?;observability::init(c.observability.log_format=="json");let (execution,state)=dependencies(&c).await?;if c.mode==Mode::Live{let name=c.execution.live_signer_env.as_deref().context("missing signer env")?;let _=std::env::var(name).context("live signer secret unavailable")?;tracing::warn!(cap=%c.risk.max_live_capital_usd,"live mode explicitly armed") ;process_jsonl(&c,&state,&execution).await?;}else{let paper=PaperExecutor::new(execution,c.runtime.paper_fill_haircut_bps);process_jsonl(&c,&state,&paper).await?;}Ok(())}
