use crate::{config::types::{Config,Mode}, domain::{market::MarketSnapshot,token::TokenSafety,trade::{OrderKind,OrderRecord,OrderSide,OrderState},wallet::WalletStats}, economics::{CostModel,EconomicGate,ExpectedValue}, execution::{ExecutionRequest,Executor}, portfolio::Portfolio, risk::RiskEngine, storage::StateStore, strategy::{evaluate_signal,StrategyDecision}};
use anyhow::Context;
use chrono::Utc;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sha2::{Digest,Sha256};

/// Explicit, timestamped boundary between a verified collector and this trading
/// process. A missing/incomplete record is rejected; it is never synthesized.
#[derive(Debug, Deserialize, Serialize)] pub struct CandidateInput { pub mint:String, #[serde(default)] pub token_decimals:Option<u8>, #[serde(default)] pub base_mint_decimals:Option<u8>, pub input_amount:u64, pub position_usd:Decimal, pub expected_gross_return_pct:Decimal, pub market:MarketSnapshot, pub safety:TokenSafety, pub wallets:Vec<WalletStats>, pub costs:CostModel }
pub async fn process_jsonl(config:&Config, store:&StateStore, executor:&dyn Executor)->anyhow::Result<()> {
 let Some(path)=config.runtime.signal_feed_path.as_deref().filter(|s|!s.is_empty()) else { tracing::warn!("no verified signal feed configured; refusing to generate synthetic trades"); return Ok(()) };
 let data=std::fs::read_to_string(path).with_context(||format!("read signal feed {path}"))?; let mut portfolio=Portfolio::default(); let mut risk=RiskEngine::new(config.risk.clone(),config.risk.starting_capital_usd);
 for line in data.lines().filter(|l|!l.trim().is_empty()) { let c:CandidateInput=serde_json::from_str(line).context("parse candidate JSONL")?; let now=Utc::now(); let (Some(token_decimals),Some(base_mint_decimals))=(c.token_decimals,c.base_mint_decimals) else { tracing::warn!(mint=%c.mint,"candidate is missing canonical mint decimals"); continue }; if c.market.observed_at>now || c.safety.observed_at>now { tracing::warn!(mint=%c.mint,"rejected future-dated candidate"); continue }
  if c.costs.input.position_size_usd!=c.position_usd { tracing::warn!(mint=%c.mint,"candidate position and economic model disagree"); continue } store.record_observation("candidate",c.market.observed_at,c.market.received_at,&c)?; let gate=EconomicGate{round_trip_cost_threshold_pct:config.economics.round_trip_cost_threshold_pct};if gate.check(&c.costs).is_err(){tracing::info!(mint=%c.mint,"economic cost gate rejected candidate");continue}let expected=ExpectedValue::estimate(c.expected_gross_return_pct,&c.costs,Decimal::ZERO,Decimal::ZERO,config.economics.uncertainty_haircut_pct)?;
  let wallets:Vec<&WalletStats>=c.wallets.iter().filter(|w|w.updated_at<=c.market.observed_at).collect(); let signal=match evaluate_signal(config,&c.mint,&wallets,&c.market,&c.safety,&expected){StrategyDecision::Accepted(s)=>s,StrategyDecision::Rejected(reason)=>{tracing::info!(mint=%c.mint,%reason,"strategy rejected candidate");continue}};
  if c.position_usd<=Decimal::ZERO || c.position_usd>config.risk.max_live_capital_usd { tracing::warn!(mint=%c.mint,"position exceeds configured live-capital cap or is invalid"); continue } risk.authorize(c.position_usd,c.market.liquidity_usd,config.execution.slippage_bps as u32,now).map_err(|e|anyhow::anyhow!(e))?;
  let mut hash=Sha256::new();hash.update(signal.id.as_bytes());hash.update(c.mint.as_bytes());hash.update(c.input_amount.to_le_bytes());let key=format!("{:x}",hash.finalize());let position_id=uuid::Uuid::new_v4().to_string();let mut order=OrderRecord{id:uuid::Uuid::new_v4().to_string(),signal_id:signal.id,mint:c.mint.clone(),kind:OrderKind::Entry,position_id:Some(position_id.clone()),side:OrderSide::Buy,input_mint:Some(config.strategy.base_mint.clone()),output_mint:Some(c.mint.clone()),input_amount_atomic:Some(c.input_amount),state:OrderState::Pending,idempotency_key:key,created_at:now,signature:None,error:None};if !store.reserve_order(&order)?{tracing::warn!(mint=%c.mint,"duplicate order blocked");continue}
  let quote=executor.quote(&config.strategy.base_mint,&c.mint,c.input_amount,config.execution.slippage_bps).await?;let min_output=quote.output_amount.saturating_mul((10_000-config.execution.slippage_bps as u64) as u64)/10_000;match executor.execute(ExecutionRequest{order_id:order.id.clone(),quote,max_slippage_bps:config.risk.max_slippage_bps,min_output_amount:min_output}).await { Ok(fill)=>{order.state=OrderState::Confirmed;order.signature=Some(fill.signature.clone());store.update_order(&order)?;store.save_fill(&fill)?;portfolio.apply_entry(c.mint.clone(),config.strategy.base_mint.clone(),token_decimals,base_mint_decimals,position_id,&fill,c.market.price_usd,order.signal_id.clone(),c.costs.clone()).map_err(anyhow::Error::msg)?;if let Some(p)=portfolio.position(&c.mint){store.save_position(p)?}tracing::info!(order_id=%order.id,mint=%c.mint,signature=%fill.signature,"confirmed fill persisted");},Err(e)=>{order.state=if matches!(e,crate::execution::ExecutionError::Unknown(_)){OrderState::Unknown}else{OrderState::Failed};order.error=Some(e.to_string());store.update_order(&order)?;tracing::error!(order_id=%order.id,error=%e,"execution not confirmed; no resend performed");}}
 }
 if config.mode==Mode::Live && store.incomplete_orders()?.iter().any(|o|o.state==OrderState::Unknown){anyhow::bail!("unknown transaction remains; live entries remain blocked")}; Ok(())
}
